apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: make-white-label-documentation
  annotations:
    github.com/project-slug: integromat/make-white-label-documentation
spec:
  type: documentation
  lifecycle: production
  owner: group:default/tech-writers
  partOfCoreProduct: false
